export default {
  "-- agentic-engineering-patterns": { "type": "separator", "title": "Agentic Engineering Patterns" },
  "what-is-agentic-engineering": "What is agentic engineering?",
  "code-is-cheap": "Writing code is cheap now",
  "hoard-things-you-know-how-to-do": "Hoard things you know how to do",
  "better-code": "AI should help us produce better code",
  "anti-patterns": "Anti-patterns: things to avoid",
  "how-coding-agents-work": "How coding agents work",
  "using-git-with-coding-agents": "Using Git with coding agents",
  "subagents": "Subagents",
  "red-green-tdd": "Red/green TDD",
  "first-run-the-tests": "First run the tests",
  "agentic-manual-testing": "Agentic manual testing",
  "linear-walkthroughs": "Linear walkthroughs",
  "interactive-explanations": "Interactive explanations",
  "gif-optimization": "GIF optimization tool using WebAssembly and Gifsicle",
  "prompts": "Prompts I use",
  "-- blog-posts": { "type": "separator", "title": "Blog Posts" },
  "niche-museums-kepler": "Weeknotes: Niche Museums, Kepler, Trees and Streaks",
  "better-presentations": "Better presentations through storytelling and STAR moments",
  "the-perfect-commit": "The Perfect Commit",
  "annotated-presentations": "How I make annotated presentations",
  "ai-in-2023": "Stuff we figured out about AI in 2023",
  "claude-and-chatgpt-case-study": "Claude and ChatGPT for ad-hoc sidequests",
  "building-c-extensions-for-sqlite-with-chatgpt-code-interpreter": "Building and testing C extensions for SQLite with ChatGPT Code Interpreter",
  "ocr-pdfs-images": "Running OCR against PDFs and images directly in your browser",
  "slop": "Slop is the new name for unwanted AI-generated content",
  "michael-wooldridge": "Carl Hewitt recently remarked that the question what is an agent",
  "llms-in-2024": "Things we learned about LLMs in 2024",
  "a-computer-can-never-be-held-accountable": "A computer can never be held accountable",
  "vibe-coding": "Not all AI-assisted programming is vibe coding (but vibe coding rocks)",
  "gemini-image-segmentation": "Image segmentation using Gemini 2.5",
  "six-months-in-llms": "The last six months in LLMs, illustrated by pelicans on bicycles",
  "the-lethal-trifecta": "The lethal trifecta for AI agents: private data, untrusted content, and external communication",
  "vibe-scraping": "Vibe scraping and vibe coding a schedule app for Open Sauce 2025 entirely on my phone",
  "sloccount-in-webassembly": "SLOCCount in WebAssembly",
  "claude-code-for-web-video": "Video: Building a tool to copy-paste share terminal sessions using Claude Code for web",
  "github-universe-badge": "Hacking the WiFi-enabled color screen GitHub Universe conference badge",
  "async-code-research": "Code research projects with async coding agents like Claude Code and Codex",
  "html-tools": "Useful patterns for building HTML tools",
  "code-proven-to-work": "Your job is to deliver code you have proven to work",
  "the-year-in-llms": "2025: The year in LLMs",
  "inflection": "It genuinely feels to me like GPT-5",
  "kakapo-mug": "Friend and neighbour Karen James made me a K\u0101k\u0101p\u014d mug",
  "gemini-31-pro": "Gemini 3",
  "agentic-engineering-patterns": "Writing about Agentic Engineering Patterns",
  "present": "I vibe coded my dream macOS presentation app",
}
